namespace: homolog

resources:
  - ../../base
  - namespace.yaml

patches:
  - target:
      kind: Ingress
      name: ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: frontend-hml.localtest.me
      - op: replace
        path: /spec/rules/1/host
        value: backend-hml.localtest.me

  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env
        value:
          - name: NODE_ENV
            value: "staging"
