namespace: homolog

resources:
  - ../../base
  - namespace.yaml

patches:
  - target:
      kind: Ingress
      name: ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: frontend-hml.localtest.me
      - op: replace
        path: /spec/rules/1/host
        value: backend-hml.localtest.me

  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/tadeubdev/k8s-estudos-backend:homolog-0.1.4

  - target:
      kind: Deployment
      name: frontend
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/tadeubdev/k8s-estudos-frontend:homolog-0.1.5
