namespace: prod

resources:
  - ../../base
  - namespace.yaml
  - hpa.yaml

patches:
  - target:
      kind: Ingress
      name: ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: frontend.localtest.me
      - op: replace
        path: /spec/rules/1/host
        value: backend.localtest.me

  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/tadeubdev/k8s-estudos-backend:__IMAGE_TAG__

  - target:
      kind: Deployment
      name: frontend
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/tadeubdev/k8s-estudos-frontend:__IMAGE_TAG__
