kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: estudo
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 80
        hostPort: 8083
        protocol: TCP
      - containerPort: 443
        hostPort: 8443
        protocol: TCP
